### ISSUE TITLE
Exception after upgrading to 0.8.0

### ISSUE THREAD

**Issue by felixb** [flosell/lambdacd#105]
I got the following exception after upgrading to 0.8.0.
Running `lein clean` fixed the issue.

```
Exception in thread "async-thread-macro-1" java.lang.IllegalArgumentException: No implementation of method: :next-build-number of protocol: #'lambdacd.internal.pipeline-state/PipelineStateComponent found for class: lambdacd.internal.default_pipeline_state.DefaultPipelineState
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
	at lambdacd.internal.pipeline_state$eval130$fn__159$G__121__164.invoke(pipeline_state.clj:11)
	at lambdacd.internal.execution$run.invoke(execution.clj:280)
	at lambdacd.runners$start_one_run_after_another$fn__641.invoke(runners.clj:46)
	at clojure.core.async$thread_call$fn__6228.invoke(async.clj:405)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by flosell** [comment]
Just looked at the code to double check, to me it looks fine. And since you mention that `lein clean` fixes the issue I'm guessing it's just related to some old state in the build folder. 

Thanks for reporting this anyway, maybe it's documentation for someone running into the same problem.

Closing, feel free to reopen if such a problem persists.
