### ISSUE TITLE
Exception when generating new project using lein using Oracle JDK 9

### ISSUE THREAD

**Issue by ayqazi** [flosell/lambdacd#130]
Hi,

I am trying to generate a new project with lein and get a long backtrace during it. This occurs with both OpenJDK 8, and Oracle JDK 9.

1) I downloaded the latest version of `lein`
2) I try to generate a new project with `lein new lambdacd pipeline1`
3) Output:

```
$ lein new lambdacd pipeline1
Downloading Leiningen to /home/ayqazi/.lein/self-installs/leiningen-2.7.0-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   605    0   605    0     0    960      0 --:--:-- --:--:-- --:--:--   960
100 14.6M  100 14.6M    0     0  3349k      0  0:00:04  0:00:04 --:--:-- 5238k
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(java.base@9-ea/Native Method)
        at java.lang.Class.forName(java.base@9-ea/Class.java:378)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core__init.load(Unknown Source)
        at clojure.core__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(java.base@9-ea/Native Method)
        at java.lang.Class.forName(java.base@9-ea/Class.java:378)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.lang.RT.doInit(RT.java:461)
        at clojure.lang.RT.<clinit>(RT.java:331)
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
        at java.lang.Class.forName0(java.base@9-ea/Native Method)
        at java.lang.Class.forName(java.base@9-ea/Class.java:378)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2181)
        at clojure.instant$loading__5569__auto____6869.invoke(instant.clj:9)
        at clojure.instant__init.load(Unknown Source)
        at clojure.instant__init.<clinit>(Unknown Source)
        ... 23 more
```

Anyone have any idea what's going on?

Thanks

**Comment by flosell** [comment]
To me, this looks like an issue in the java setup: 
Apparently, it can't find `java.sql.Timestamp` which is imported by the `clojure.instant` namespace. Both are in the respective standard-libraries so this shouldn't be an issue... 

A few things you can try: 

* See what happens if you try requiring `clojure.instant` on a lein-repl; do you get the same error? 
* Make sure there are no old LambdaCD lein-templates hanging around in the local maven repo (`~/.m2/repository/lambdacd/lein-template`). I don't think that's the issue but just in case. 
* Check if Leiningen is using the right java installation; Judging from the [lein-script](https://github.com/technomancy/leiningen/blob/master/bin/lein#L232), it should use `$LEIN_JAVA_CMD`, `$JAVA_CMD`, or whatever `java` command is on the path; `lein version` should tell you which JVM it is running

**Comment by ayqazi** [comment]
Ah, it was a problem with Oracle JDK 9 - it worked with OpenJDK 8. I did a purge + reinstall of Oracle JDK 9 on Ubuntu 16.04 LTS, and got the same problem.

I've updated the issue title to reflect that it's an Oracle JDK 9 issue.

ThankS

**Comment by ayqazi** [comment]
It's actually a leiningen issue too, nothing to do with lambdacd. Sorry to bother you with this, should have investigated it further. Closing topic....

**Comment by flosell** [comment]
No worries, thanks for the follow up!
