### ISSUE TITLE
0.9.5 is broken, can't find lambdacd.execution

### ISSUE THREAD

**Issue by flosell** [flosell/lambdacd#133]
The new `lambdacd.execution` namespace ended up in `src/test` and therefore isn't part of the released jar, making release 0.9.5 unusable: https://github.com/flosell/lambdacd/commit/8b10dc28b1081944caeb7dc96f7c8e2b7575e0bb#commitcomment-18998819

Thanks @elmingo for finding this!

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate lambdacd/execution__init.class or lambdacd/execution.clj on classpath., compiling:(lambdacd/runners.clj:1:1)
       	at clojure.lang.Compiler.load(Compiler.java:7239)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:551)
       	at lambdacd.core$eval38$loading__5340__auto____39.invoke(core.clj:1)
       	at lambdacd.core$eval38.invoke(core.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:551)
       	at lambdacd.steps.control_flow$eval32$loading__5340__auto____33.invoke(control_flow.clj:1)
       	at lambdacd.steps.control_flow$eval32.invoke(control_flow.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:634)
       	at clojure.core$use.doInvoke(core.clj:5843)
       	at clojure.lang.RestFn.invoke(RestFn.java:421)
       	at foo.pipeline$eval26$loading__5340__auto____27.invoke(pipeline.clj:1)
       	at foo.pipeline$eval26.invoke(pipeline.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:551)
       	at foo.core$eval20$loading__5340__auto____21.invoke(core.clj:1)
       	at foo.core$eval20.invoke(core.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at user$eval5$fn__7.invoke(form-init685419513105283702.clj:1)
       	at user$eval5.invoke(form-init685419513105283702.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6772)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
       	at clojure.main$load_script.invoke(main.clj:275)
       	at clojure.main$init_opt.invoke(main.clj:280)
       	at clojure.main$initialize.invoke(main.clj:308)
       	at clojure.main$null_opt.invoke(main.clj:343)
       	at clojure.main$main.doInvoke(main.clj:421)
       	at clojure.lang.RestFn.invoke(RestFn.java:421)
       	at clojure.lang.Var.invoke(Var.java:383)
       	at clojure.lang.AFn.applyToHelper(AFn.java:156)
       	at clojure.lang.Var.applyTo(Var.java:700)
       	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate lambdacd/execution__init.class or lambdacd/execution.clj on classpath.
       	at clojure.lang.RT.load(RT.java:449)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:457)
       	at lambdacd.runners$eval10330$loading__5340__auto____10331.invoke(runners.clj:1)
       	at lambdacd.runners$eval10330.invoke(runners.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
```

**Comment by flosell** [comment]
Fixed and released in 0.10.0
