### ISSUE TITLE
Use CredentialsProvider

### ISSUE THREAD

**Issue by nmarquesantos** [flosell/lambdacd#141]
Hi guys

Would it be possible to specify a credentials provider when cloning a repo?

I don't see any other way of cloning a private repo via https.

**Comment by nmarquesantos** [comment]
actually on investigating this a bit further, I'm happy to make this change and do a pull request if you agree with the approach

**Comment by flosell** [comment]
Hi, 
I'm guessing you tried something like ```https://username:password@repo.com``` already?
I'm also developing a separate library for git-support that uses JGit: https://github.com/flosell/lambdacd-git
I haven't tested it with private https repos but you could at least give it a try. 

The lambdacd-git library is supposed to replace the git-implementation in the core of lambdacd at some point so I'd prefer features to be added there. Nevertheless, I wouldn't be totally opposed to a PR in the old implementation as well if this helps you short term and doesn't introduce massive additional complexity.

**Comment by nmarquesantos** [comment]
That's correct.

This is the stacktrace I get back if I try specifying user:password in the url

`09:20:51.878 [async-thread-macro-3] WARN  lambdacd-git.core - could not get current revision for ref lambdacd_git.git$match_ref$fn__10689@36c38a26 on https://nuno:password@repo.com/repo.git
org.eclipse.jgit.api.errors.TransportException: https://nuno@repo.com/repo.git Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:223) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
	at org.eclipse.jgit.api.LsRemoteCommand.callAsMap(LsRemoteCommand.java:177) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
	at lambdacd_git.git$current_revisions.invoke(git.clj:29) ~[na:na]
	at lambdacd_git.core$current_revision_or_nil.invoke(core.clj:41) ~[na:na]
	at lambdacd_git.core$wait_for_revision_changed$fn__10915.invoke(core.clj:82) [na:na]
	at lambdacd_git.core$wait_for_revision_changed.invoke(core.clj:80) [na:na]
	at lambdacd_git.core$wait_for_git$fn__10934.invoke(core.clj:134) [na:na]
	at lambdacd_git.core$wait_for_git.doInvoke(core.clj:128) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:464) [clojure-1.7.0.jar:na]
	at my_first_pipeline.steps$wait_for_repo.invoke(steps.clj:9) [na:na]
	at lambdacd.internal.execution$execute_or_catch.invoke(execution.clj:54) [na:na]
	at lambdacd.internal.execution$execute_step.invoke(execution.clj:131) [na:na]
	at lambdacd.core$execute_step.invoke(core.clj:58) [na:na]
	at lambdacd.steps.control_flow$either_step_result_producer$fn__10500$fn__10501.invoke(control_flow.clj:34) [na:na]
	at clojure.core.async$thread_call$fn__7716.invoke(async.clj:405) [na:na]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
`

**Comment by flosell** [comment]
Ah, ok, you already are using the new lambdacd-git library. In this case, all good, I agree: Adding the ability to specify a credentials-provider seems to be the best way forward. I'd welcome a PR on this

**Comment by flosell** [comment]
Fixed in version [`0.2.1`](https://github.com/flosell/lambdacd-git/releases/tag/0.2.1) of `lambdacd-git`
