### ISSUE TITLE
automating the build and deploy of a nodejs application 

### ISSUE THREAD

**Issue by utkarshu91** [flosell/lambdacd#164]
hi,
this is an amazing idea of converting the process of build and deploy pipeline into the code
i'm trying to set this up for my nodejs web application which needs to be build on a local machine and then deployed in a docker container but i'm kind of struggling in finding the proper documentation for these things to put to work.
And i also have a question that when i change home-dir in core.clj under
config {:home-dir home-dir
it gives me an error that invalid token
i'd really appreciate if you could help me out with this.
 @utkarshu91
  
            
 
Write

**Comment by flosell** [comment]
I think I need a few more details to help you there: 

Regarding your build and deployment, is your question about how to distribute a pipeline across multiple machines (it's tricky and I would try to avoid doing this)? Is it on how to get the build and deployment done in general (In doubt, I'd get started just setting these tasks up in shell scripts, put them next to your code and have LambdaCD call them using `lambdacd.steps.shell/bash`. You can try building more fancy stuff on top of it later on)?

Regarding your home-dir, could you just post a snippet of the code that's causing the issue and the error/stacktrace you are getting?

**Comment by utkarshu91** [comment]
hi 
thanks for the reply 
my objective is to build the application in my local machine and deploy it in a docker container in my local machine itself 
i think it will work for me if i'll put my task in a shell script and let lambdaCD call them but the question is how can i call that script and where do i have to put that script so that lambdaCD can call it

my core.clj file looks like 

(ns test1.core
  (:require
      [test1.pipeline :as pipeline]
      [ring.server.standalone :as ring-server]
      [lambdacd.ui.ui-server :as ui]
      [lambdacd.runners :as runners]
      [lambdacd.util :as util]
      [lambdacd.core :as lambdacd]
      [clojure.tools.logging :as log])
  (:gen-class))

(defn -main [& args]
      (let [;; the home dir is where LambdaCD saves all data.
            ;; point this to a particular directory to keep builds around after restarting
            home-dir (util/create-temp-dir)
            config {:home-dir /home/utkarsh/data/
                    :name "test1"}
            ;; initialize and wire everything together
            pipeline (lambdacd/assemble-pipeline pipeline/pipeline-def config)
            ;; create a Ring handler for the UI
            app (ui/ui-for pipeline)]
           (log/info "LambdaCD Home Directory is " home-dir)
           ;; this starts the pipeline and runs one build after the other.
           ;; there are other runners and you can define your own as well.
           (runners/start-one-run-after-another pipeline)
           ;; start the webserver to serve the UI
           (ring-server/serve app {:open-browser? false
                                   :port 8081})))




so when i do lein run, below is the output

WARNING: You're currently running as root; probably by accident.
Press control-C to abort or Enter to continue as root.
Set LEIN_ROOT to disable this warning.

WARNING: alias already refers to: #'clojure.core/alias in namespace: test1.pipeline, being replaced by: #'lambdacd.steps.control-flow/alias
Exception in thread "main" java.lang.RuntimeException: Invalid token: /home/utkarsh/data/, compiling:(test1/core.clj:17:0)
	at clojure.lang.Compiler.load(Compiler.java:7234)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval5$fn__7.invoke(form-init439548526557333155.clj:1)
	at user$eval5.invoke(form-init439548526557333155.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Invalid token: /home/utkarsh/data/
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.LispReader.interpretToken(LispReader.java:390)
	at clojure.lang.LispReader.read(LispReader.java:283)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7222)
	... 33 more

**Comment by flosell** [comment]
Looks like you are missing the quotes for home-dir. This should work: 
```clojure
(let [; ... 
       config {:home-dir "/home/utkarsh/data/"
                   :name "test1"}
; ...
```

In terms of how to wire shell scripts in a repository and LambdaCD together, have a look at this example: 
https://github.com/flosell/lambdacd-git/blob/master/example/lambdacd_git/example/simple_pipeline.clj

It uses the [lambdacd-git](https://github.com/flosell/lambdacd-git) library (you might need to add it in your `project.clj`) to clone a repository and then run a shell-command (in this case just `ls`) in the directory where the repo was cloned.

**Comment by utkarshu91** [comment]
Thank you, 
for the help, i think now i will be able to complete the pipeline.
