### ISSUE TITLE
Is 0.14.0 safe?

### ISSUE THREAD

**Issue by Atsman** [flosell/lambdacd#184]
Hi, i just updated version, removed labmdaui, and i still see error:
```text
WARNING: alias already refers to: #'clojure.core/alias in namespace: autoscanner-cd.pipeline, being replaced by: #'lambdacd.steps.control-flow/alias
16:19:33.221 [main] INFO  autoscanner-cd.core - LambdaCD Home Directory is  /var/folders/l0/s7hbjt716vn6ldx36xzr8z0c0000gn/T/lambdacd6499035821693321349
Exception in thread "async-thread-macro-1" java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
	at clojure.lang.RT.seqFrom(RT.java:528)
	at clojure.lang.RT.seq(RT.java:509)
	at clojure.lang.RT.more(RT.java:684)
	at clojure.core$rest__4114.invoke(core.clj:73)
	at lambdacd.presentation.pipeline_structure$container_step_representation.invoke(pipeline_structure.clj:113)
	at lambdacd.presentation.pipeline_structure$step_display_representation_internal.invoke(pipeline_structure.clj:132)
	at lambdacd.presentation.pipeline_structure$seq_to_display_representations$fn__8902.invoke(pipeline_structure.clj:86)
	at clojure.core$map_indexed$mapi__6824$fn__6825.invoke(core.clj:7017)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$print_sequential.invoke(core_print.clj:47)
	at clojure.core$fn__5839.invoke(core_print.clj:155)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.core$pr_on.invoke(core.clj:3548)
	at clojure.core$pr.invoke(core.clj:3560)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$pr_str.doInvoke(core.clj:4563)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at lambdacd.internal.default_pipeline_state_persistence$write_build_data_edn.invoke(default_pipeline_state_persistence.clj:93)
	at lambdacd.internal.default_pipeline_state.DefaultPipelineState.consume_pipeline_structure(default_pipeline_state.clj:42)
	at lambdacd.state.core$consume_pipeline_structure.invoke(core.clj:49)
	at lambdacd.execution.internal.pipeline$run_pipeline.invoke(pipeline.clj:11)
	at lambdacd.execution.core$run_pipeline.invoke(core.clj:21)
	at lambdacd.runners$start_one_run_after_another$fn__10519.invoke(runners.clj:51)
	at clojure.core.async$thread_call$fn__6137.invoke(async.clj:441)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Do you know what the problem is?

**Comment by Atsman** [comment]
Sorry, that was my bad :)
