### ISSUE TITLE
`./go setup` failing due to "No such namespace: doo.runner"

### ISSUE THREAD

**Issue by philwhln** [flosell/lambdacd#81]
So far, I've been unsuccessful in building the clojure script due to this error. Anything I'm missing?

```
phil@pro ~/s/o/lambdacd> ./go setup
 ☑ Leiningen installed
 ☑ NPM installed

Installing NPM dependencies...
npm WARN EPACKAGEJSON lambdacd@ No repository field.
npm WARN EPACKAGEJSON lambdacd@ No license field.
Building CSS from LESS...

> lambdacd@ build /Users/phil/src/otono/lambdacd
> npm run build:css


> lambdacd@ build:css /Users/phil/src/otono/lambdacd
> node_modules/less/bin/lessc src/less/main.less | node_modules/postcss-cli/bin/postcss --use autoprefixer -o resources/public/css/main.css

Compiling ClojureScript...
Compiling "/Users/phil/src/otono/lambdacd/target/cljsbuild-main.js" from ["src/cljs" "test/cljs"]...
Compiling "/Users/phil/src/otono/lambdacd/target/cljsbuild-main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:test/cljs/lambdacd/runner.cljs {:file #object[java.io.File 0x5aec151b "test/cljs/lambdacd/runner.cljs"]}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.compiler$compile_file$fn__3198.invoke(compiler.cljc:1254)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1216)
	at cljs.compiler$compile_root.invoke(compiler.cljc:1291)
	at cljs.closure$compile_dir.invoke(closure.clj:438)
	at cljs.closure$eval3581$fn__3582.invoke(closure.clj:478)
	at cljs.closure$eval3533$fn__3534$G__3524__3541.invoke(closure.clj:383)
	at cljs.closure$eval3594$fn__3595.invoke(closure.clj:492)
	at cljs.closure$eval3533$fn__3534$G__3524__3541.invoke(closure.clj:383)
	at cljsbuild.compiler.SourcePaths$fn__4074.invoke(compiler.clj:67)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$mapcat.doInvoke(core.clj:2660)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at cljsbuild.compiler.SourcePaths._compile(compiler.clj:67)
	at cljs.closure$build.invoke(closure.clj:1671)
	at cljs.closure$build.invoke(closure.clj:1627)
	at cljsbuild.compiler$compile_cljs$fn__4085.invoke(compiler.clj:81)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:80)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:187)
	at user$eval4219$iter__4255__4259$fn__4260$fn__4278.invoke(form-init7713960503142719066.clj:1)
	at user$eval4219$iter__4255__4259$fn__4260.invoke(form-init7713960503142719066.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:674)
	at clojure.core$next__4112.invoke(core.clj:64)
	at clojure.core$dorun.invoke(core.clj:3010)
	at clojure.core$doall.invoke(core.clj:3025)
	at user$eval4219.invoke(form-init7713960503142719066.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No such namespace: doo.runner, could not locate doo/runner.cljs, doo/runner.cljc, or Closure namespace "doo.runner" {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:535)
	at cljs.analyzer$error.invoke(analyzer.cljc:533)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1637)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2470)
	at cljs.analyzer$analyze_STAR_$fn__1987.invoke(analyzer.cljc:2551)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
	at clojure.core$reduce.invoke(core.clj:6518)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2551)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2566)
	at cljs.compiler$compile_file_STAR_$fn__3157.invoke(compiler.cljc:1125)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1053)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1076)
	at cljs.compiler$compile_file$fn__3198.invoke(compiler.cljc:1237)
	... 46 more
Subprocess failed
```

**Comment by flosell** [comment]
Thanks for pointing this out!
Looks like lein-doo needs to added as a dependency as well. No idea why it worked for me until now. 

Can you try again?

**Comment by philwhln** [comment]
Works, thanks!
